#!/bin/sh
set -euo pipefail

export HOME="${LAMBDA_TASK_ROOT}"

if test -f mix.exs
then
 export MIX_ENV=${MIX_ENV:-prod}
 mix compile
 export ERL_LIBS="${LAMBDA_TASK_ROOT}/_build/${MIX_ENV}/lib"
else
 export ERL_LIBS="${LAMBDA_TASK_ROOT}/lib"
fi

elixir -e "LambdaRuntime.run()"
