#!/bin/sh
set -xeuo pipefail

export HOME="/tmp/task"

echo "HOME=${HOME} ($(pwd))"

ls -la
id
ls -la /tmp

if test -f mix.exs
then
  mkdir -p ${HOME}
  cp -r ${LAMBDA_TASK_ROOT}/* ${HOME}
  cd ${HOME}

  export MIX_ENV=${MIX_ENV:-prod}
  export ERL_LIBS="${HOME}/_build/${MIX_ENV}/lib"

  mix compile
else
  export ERL_LIBS="${LAMBDA_TASK_ROOT}/lib"
fi

elixir -e "LambdaRuntime.run()"
